package inozemtsev.coursework.easystat.utils;

public enum EasyStatRequestType {
    SIGN_UP,
    SIGN_IN,
    GET_ALL_QUESTIONNAIRES_WITH_ACCESS,
    GET_QUESTIONS_FOR_QUESTIONNAIRE,
    SEND_ANSWER,
    FIND_QUESTIONNAIRE_WITH_USER_ID,
    FIND_QUESTIONNAIRE_BY_ID,
    FIND_QUESTIONNAIRES_WITH_NAME,
    GET_STAT_FOR_USER_QUESTIONNAIRES,
    GET_STAT_FOR_QUESTION,
    CREATE_NEW_QUESTIONNAIRE,
    CREATE_NEW_QUESTIONS
}
